### PR TITLE
Annotate functions for CUDA.

### PR DESCRIPTION
**Pull request by alliepiper**
This patch allows tao::tuple objects to work directly in CUDA code.

### CODE REVIEW

**Comment by d-frey** [comment]
Thanks. I have to admit that taocpp/tuple has not been maintained well and it was initially created to prove a point about avoiding recursions, so I'm currently considering whether to keep it as a project for taocpp or to archive it. Are you actively using it for something?

**Comment by alliepiper** [comment]
We started using it at Kitware in VTKm (https://gitlab.kitware.com/vtk/vtk-m) recently. We needed a tuple implementation that would work on across platforms and also with CUDA, so the obvious choices of `std::tuple` and `thrust::tuple` don't work. `std::tuple` isn't usable from CUDA, but we also don't require CUDA so `thrust::tuple` isn't always available. It ended up being easier to embed an implementation and mark it up for CUDA ourselves.

Additionally, we're a large template library and compile times are an issue, so this tuple implementation was an especially good fit. It's worked well for us so far -- thanks for writing this and making it easily usable!

I also have a few patches that fix issues on GCC 5, 7, and MSVC2017 that I'll push shortly if you're interested in them.

**Comment by d-frey** [comment]
Good to know. I'd be interested in fixing the issues with GCC 5 / 7 and MSVC 2011, but I need to catch up on maintenance first. This means I'll fix the macro names, move parts of your patch to taocpp/sequences, etc. This might already resolve some issues. Please give me some time for the basics and then you can check which of your fixes are still needed.

**Comment by alliepiper** [comment]
Sounds good. I've got a branch with the other compiler fixes ready at #3 -- feel free to pick what looks reasonable out of there.

**Comment by d-frey** [comment]
I'll have a look at these fixes later, but I'm wondering about something else: You added the annotation to `integer_sequence::size()` - but to the version in `git-subtree/*` which is not used by the tuple. Is this part of the patch actually needed? (The `git-subtree/*` was a failed experiment, so I will remove it anyways)

If it is needed, I need to apply it to taocpp/sequences, but I guess it is superfluous as `size()` is only used by tuple only in compile-time contexts and therefore no code is ever generated. It also solves another problem: With newer standards `tao::integer_sequence` is just a type alias for `std::sequence` and our own implementation is never used anyways.

**Comment by alliepiper** [comment]
It looks like the changes under `seq/` can be removed without breaking our code. Feel free to drop those.

**Pull request merged**
